Add forms
trace-kadenyi/rails-blog-app pull request #8
Opened 2022-10-27 13:38 UTC by TracK92

- [ ] Create a method called current_user in the  `ApplicationController`.
- [ ] Create forms to perform the following functions:

1) Creates a Post on behalf of the current_user.
2) Create a comment on behalf of the current_user.
3) Allow Users to add likes to Posts.

2022-10-27 14:35 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Tracey, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
README is professional. :heavy_check_mark:
Git flow is followed. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-10-27 14:35 UTC, SajjadAhmad14 commented on app/views/posts/new.html.erb
> +<%= form_with model: @post do |form| %>
The user should be able to create a post on the behalf of currently logged-in user. Kindly see the error which occurs while trying to create a new post.

2022-10-27 14:35 UTC, SajjadAhmad14 commented on app/controllers/comments_controller.rb
> +  def new
The user should be able to create a comment on behalf of the currently logged-in user of the app.

2022-10-27 14:35 UTC, SajjadAhmad14 commented on app/controllers/likes_controller.rb
> +  def create
A user should be able to add a like to posts.

2022-10-27 14:35 UTC, SajjadAhmad14 commented on config/routes.rb
> +  resources :comments, only: [:new, :create]
A comment is added to a specific post so the controller needs a post id. Kindly add new and create routes in such a way that they carry post id with them for comments controller.

2022-10-27 14:35 UTC, SajjadAhmad14 commented on config/routes.rb
> +  resources :likes, only: [:new, :create]
A like is added to a specific post so the controller needs a post id. Kindly add new and create routes in such a way that they carry post id with them for likes controller.

2022-10-28 16:08 UTC, ShoiraTa commented
## **STATUS: APPROVED  🟢 ** 
------
### Hi @TracK92 , 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

### Highlights:
 ✔️ Project is setup correctly
 ✔️ All linters are passing
✔️ Correct gitflow
 ✔️ Professional documentation

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![image](https://user-images.githubusercontent.com/77038610/192113752-c316f323-e076-4961-85fa-20b64eb8b6ed.png)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@shoirata] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 16:33 UTC, merged